/* Regenerate src/catalogSnapshot.ts from the live API.
 *
 *   node scripts/snapshot-catalog.mjs           write it
 *   node scripts/snapshot-catalog.mjs --check   exit 1 if it has drifted
 *
 * Optional: CATALOG_URL to point at another API (e.g. a local one). */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const target = join(here, '..', 'src', 'catalogSnapshot.ts')
const url = process.env.CATALOG_URL ?? 'https://api.farmrx.dertwerk.com/api/v1/apps'

const res = await fetch(url)
if (!res.ok) {
  console.error(`catalog fetch failed: ${res.status} ${url}`)
  process.exit(2)
}
const apps = await res.json()
const body =
  `/* GENERATED by scripts/snapshot-catalog.mjs from ${url.replace(/\/api\/v1\/apps$/, '')} -- do not edit. */\n` +
  `import type { SuiteApp } from './catalog'\n\n` +
  `export const CATALOG_SNAPSHOT: SuiteApp[] = ${JSON.stringify(apps, null, 2)}\n`

if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8').replace(/\r\n/g, '\n')
  const strip = (s) => s.split('\n').slice(1).join('\n')
  if (strip(current) !== strip(body)) {
    console.error('src/catalogSnapshot.ts is out of date with the live catalog. Run: node scripts/snapshot-catalog.mjs')
    process.exit(1)
  }
  console.log('catalog snapshot matches the live API')
} else {
  writeFileSync(target, body)
  console.log(`wrote ${apps.length} apps to src/catalogSnapshot.ts`)
}
